#!/usr/bin/env python3
"""Vendor Arimo Bold (Arial-metric-compatible, OFL) glyph OUTLINES + advances
into a TypeScript module. Real typography: true contours, true spacing.
"""
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont
from fontTools.pens.recordingPen import DecomposingRecordingPen

NEED = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ.-:"

font = TTFont("arimo-var.ttf")
instantiateVariableFont(font, {"wght": 700}, inplace=True)
upem = font["head"].unitsPerEm
cap = font["OS/2"].sCapHeight
cmap = font.getBestCmap()
glyphset = font.getGlyphSet()
hmtx = font["hmtx"]

def flatten_q(p0, pts, out, steps=10):
    """qCurveTo: sequence of off-curves with final on-curve; implied on-curve
    midpoints between consecutive off-curves."""
    if pts[-1] is None:  # TrueType all-offcurve contour (rare) — not expected
        raise ValueError("unsupported closed quad contour")
    offs = list(pts[:-1])
    last = pts[-1]
    cur = p0
    segs = []
    for i, off in enumerate(offs):
        if i < len(offs) - 1:
            nxt = offs[i + 1]
            end = ((off[0] + nxt[0]) / 2, (off[1] + nxt[1]) / 2)
        else:
            end = last
        segs.append((cur, off, end))
        cur = end
    for (a, c, b) in segs:
        for k in range(1, steps + 1):
            t = k / steps
            mt = 1 - t
            x = mt * mt * a[0] + 2 * mt * t * c[0] + t * t * b[0]
            y = mt * mt * a[1] + 2 * mt * t * c[1] + t * t * b[1]
            out.append((x, y))

def flatten_c(p0, p1, p2, p3, out, steps=12):
    for k in range(1, steps + 1):
        t = k / steps
        mt = 1 - t
        x = mt**3 * p0[0] + 3 * mt**2 * t * p1[0] + 3 * mt * t**2 * p2[0] + t**3 * p3[0]
        y = mt**3 * p0[1] + 3 * mt**2 * t * p1[1] + 3 * mt * t**2 * p2[1] + t**3 * p3[1]
        out.append((x, y))

def simplify(pts, tol=6.0):  # font units at upem 2048; ~0.3% of em
    if len(pts) <= 3:
        return pts
    out = [pts[0]]
    for p in pts[1:-1]:
        lx, ly = out[-1]
        if (p[0] - lx) ** 2 + (p[1] - ly) ** 2 >= tol * tol:
            out.append(p)
    out.append(pts[-1])
    return out

glyphs = {}
for ch in NEED:
    gname = cmap[ord(ch)]
    pen = DecomposingRecordingPen(glyphset)
    glyphset[gname].draw(pen)
    contours = []
    cur = []
    start = None
    pos = None
    for op, args in pen.value:
        if op == "moveTo":
            if cur:
                contours.append(cur)
            cur = [args[0]]
            start = args[0]
            pos = args[0]
        elif op == "lineTo":
            cur.append(args[0])
            pos = args[0]
        elif op == "qCurveTo":
            flatten_q(pos, list(args), cur)
            pos = args[-1]
        elif op == "curveTo":
            flatten_c(pos, args[0], args[1], args[2], cur)
            pos = args[2]
        elif op == "closePath":
            if cur:
                if cur[0] != cur[-1]:
                    cur.append(cur[0])
                contours.append(simplify(cur))
                cur = []
        elif op == "endPath":
            if cur:
                contours.append(simplify(cur))
                cur = []
    if cur:
        contours.append(simplify(cur))
    adv = hmtx[gname][0]
    glyphs[ch] = {"adv": adv, "contours": contours}
    print(f"{ch!r}: {len(contours)} contours, {sum(len(c) for c in contours)} pts, adv {adv}")

space_adv = hmtx[cmap[ord(" ")]][0]

def fmt_pts(pts):
    return "[" + ",".join(f"[{p[0]:.0f},{p[1]:.0f}]" for p in pts) + "]"

lines = []
lines.append("// Vendored glyph outlines from Arimo Bold (Google Fonts) — metric-compatible")
lines.append("// with Arial. SIL Open Font License 1.1 — see FONT-LICENSE-ARIMO.")
lines.append("// Real typography: true contours + true advance widths, y-UP font units.")
lines.append("// Generated by scripts/convert_arimo_font.py — do not edit by hand.")
lines.append("export type Contour = [number, number][];")
lines.append("export interface OutlineGlyph { adv: number; contours: Contour[]; }")
lines.append("")
lines.append(f"export const UPEM = {upem};")
lines.append(f"export const CAP_U = {cap};")
lines.append(f"export const ADV_SPACE_U = {space_adv};")
lines.append("")
lines.append("export const GLYPHS: Record<string, OutlineGlyph> = {")
import json
for ch, gl in sorted(glyphs.items()):
    cs = ",".join(fmt_pts(c) for c in gl["contours"])
    lines.append(f"  {json.dumps(ch)}: {{adv: {gl['adv']}, contours: [{cs}]}},")
lines.append("};")

out = "/Users/pete/Documents/GitHub/apparel-brand/src/lib/glyph/arimo.ts"
open(out, "w").write("\n".join(lines) + "\n")
import os
print("wrote", out, os.path.getsize(out), "bytes")
